export const fakeData = {
	products: {
		regular: [
			{
				id: 1,
				title: "سکه طلا",
				description: "سکه تمام بهار آزادی",
				price: "۲۵,۰۰۰,۰۰۰ تومان",
				tag: "پرفروش",
			},
			{
				id: 2,
				title: "شمش نقره",
				description: "شمش نقره ۱۰۰ گرمی",
				price: "۲,۵۰۰,۰۰۰ تومان",
				tag: "جدید",
			},
			{
				id: 3,
				title: "سکه پلاتین",
				description: "سکه پلاتین ۱ انس",
				price: "۴۵,۰۰۰,۰۰۰ تومان",
				tag: "محدود",
			},
			{
				id: 4,
				title: "شمش طلا",
				description: "شمش طلا ۵۰ گرمی",
				price: "۸۵,۰۰۰,۰۰۰ تومان",
				tag: "ویژه",
			},
			{
				id: 5,
				title: "ربع سکه",
				description: "ربع سکه بهار آزادی",
				price: "۸,۰۰۰,۰۰۰ تومان",
				tag: "پرفروش",
			},
		],
		featured: [
			{
				id: 1,
				name: "کروگرند - ۱ اونس طلای ۲۲ عیار",
				image: "/3dicons-medal-front-color-500-500.png",
				onSale: true,
			},
			{
				id: 2,
				name: "شمش پلاتین - ۱۰ اونس",
				image: "/3dicons-medal-front-color-500-500.png",
				onSale: false,
			},
			{
				id: 3,
				name: "شمش مس گایگر - ۱۰ AVDP OZ، خلوص ۹۹۹۹",
				image: "/3dicons-medal-front-color-500-500.png",
				onSale: false,
			},
			{
				id: 4,
				name: "گلدپنر - سکه نقره ۱ اونسی قابل تقسیم",
				image: "/3dicons-medal-front-color-500-500.png",
				onSale: false,
			},
			{
				id: 5,
				name: "شمش طلا ۱۰۰ گرمی (برند انتخابی)",
				image: "/3dicons-medal-front-color-500-500.png",
				onSale: false,
			},
		],
		hotItems: [
			{
				id: 1,
				name: "سکه فیلارمونیک اتریش - ۱/۲۵ اونس طلا",
				image: "/3dicons-medal-front-color-500-500.png",
				price: "۱۵۴.۱۰",
				hot: true,
			},
			{
				id: 2,
				name: "شمش نقره رویال کانادین - ۱۰ اونس",
				image: "/3dicons-medal-front-color-500-500.png",
				price: "۳۴۷.۶۰",
				hot: true,
			},
			{
				id: 3,
				name: "نیم دلار کندی نقره ۴۰٪",
				image: "/3dicons-medal-front-color-500-500.png",
				price: "۹.۵۸",
				hot: true,
			},
			{
				id: 4,
				name: "شمش طلا ۱ اونسی (برند انتخابی)",
				image: "/3dicons-medal-front-color-500-500.png",
				price: "۲,۸۱۰.۴۵",
				hot: true,
			},
			{
				id: 5,
				name: "بسته مخلوط گلدبک - ۱/۱۰۰۰ تروی اونس",
				image: "/3dicons-medal-front-color-500-500.png",
				price: "۳۴.۰۳",
				hot: true,
			},
		],
	},
	categories: [
		{
			name: "نقره",
			type: "سکه",
			typeColor: "سکه‌ها",
			image: "/3dicons-medal-front-color-500-500.png",
			href: "#",
		},
		{
			name: "طلا",
			type: "سکه",
			typeColor: "سکه‌ها",
			image: "/3dicons-medal-front-color-500-500.png",
			href: "#",
		},
		{
			name: "نقره",
			type: "شمش",
			typeColor: "شمش‌ها",
			image: "/3dicons-medal-front-color-500-500.png",
			href: "#",
		},
		{
			name: "طلا",
			type: "شمش",
			typeColor: "شمش‌ها",
			image: "/3dicons-medal-front-color-500-500.png",
			href: "#",
		},
		{
			name: "نقره",
			type: "پولک",
			typeColor: "پولک‌ها",
			image: "/3dicons-medal-front-color-500-500.png",
			href: "#",
		},
		{
			name: "طلا",
			type: "پولک",
			typeColor: "پولک‌ها",
			image: "/3dicons-medal-front-color-500-500.png",
			href: "#",
		},
		{
			name: "خرید",
			type: "مس",
			typeColor: "مس",
			image: "/3dicons-medal-front-color-500-500.png",
			href: "#",
		},
	],
};
